### Admin Login
POST https://campus-recruitment-system-aij7.onrender.com/auth/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Student Login
POST https://campus-recruitment-system-aij7.onrender.com/auth/student/login
Content-Type: application/json

{
  "rollNo": "23R21A05D6",
  "password": "vaish123"
}